/* Generated By:JJTree: Do not edit this line. AST_Literal.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Literal extends SimpleNode {
  public AST_Literal(int id) {
    super(id);
  }

  public AST_Literal(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1379e5a1bb1da6a024f90abe062bdd4 (do not edit this line) */
