/* Generated By:JJTree: Do not edit this line. AST_Statement_Switch_Pattern_Bind.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_Switch_Pattern_Bind extends SimpleNode {
  public AST_Statement_Switch_Pattern_Bind(int id) {
    super(id);
  }

  public AST_Statement_Switch_Pattern_Bind(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90f86c7fe4c77002623797e5669be068 (do not edit this line) */
