/* Generated By:JJTree: Do not edit this line. AST_Statement_For_IterateBranch.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_For_IterateBranch extends SimpleNode {
  public AST_Statement_For_IterateBranch(int id) {
    super(id);
  }

  public AST_Statement_For_IterateBranch(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8deb5ae137202d3269509e8684d6c13f (do not edit this line) */
