/* Generated By:JJTree: Do not edit this line. AST_Type_Class.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Type_Class extends SimpleNode {
  public AST_Type_Class(int id) {
    super(id);
  }

  public AST_Type_Class(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=639cf1d738fbf618f721434680b8a9e7 (do not edit this line) */
