/* Generated By:JJTree: Do not edit this line. AST_Terminator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Terminator extends SimpleNode {
  public AST_Terminator(int id) {
    super(id);
  }

  public AST_Terminator(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1cffe890beb0b3c3b76dc37e2cda41c9 (do not edit this line) */
