/* Generated By:JJTree: Do not edit this line. AST_Declaration_Tuple_Named.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Tuple_Named extends SimpleNode {
  public AST_Declaration_Tuple_Named(int id) {
    super(id);
  }

  public AST_Declaration_Tuple_Named(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d260f068646a50af2fe16cda90694581 (do not edit this line) */
