/* Generated By:JJTree: Do not edit this line. AST_Statement_If_False.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_If_False extends SimpleNode {
  public AST_Statement_If_False(int id) {
    super(id);
  }

  public AST_Statement_If_False(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a88323f83e1cdec4521bf5afc67bbb54 (do not edit this line) */
