/* Generated By:JJTree: Do not edit this line. AST_BlockUnit_Thread_Unsafe.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_BlockUnit_Thread_Unsafe extends SimpleNode {
  public AST_BlockUnit_Thread_Unsafe(int id) {
    super(id);
  }

  public AST_BlockUnit_Thread_Unsafe(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e853dc6c972b39a41ef74a8b8d7dc1e (do not edit this line) */
