/* Generated By:JJTree: Do not edit this line. AST_Declaration_Bind.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Bind extends SimpleNode {
  public AST_Declaration_Bind(int id) {
    super(id);
  }

  public AST_Declaration_Bind(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82ecc271735edf5a2645f5519c903901 (do not edit this line) */
