/* Generated By:JJTree: Do not edit this line. AST_Declaration_Tuple_Identifier_Only.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Tuple_Identifier_Only extends SimpleNode {
  public AST_Declaration_Tuple_Identifier_Only(int id) {
    super(id);
  }

  public AST_Declaration_Tuple_Identifier_Only(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c0a310e08da95f7d9c1fbdb65c96d35 (do not edit this line) */
