/* Generated By:JJTree: Do not edit this line. AST_Declaration_Tuple_Named_Arg.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Tuple_Named_Arg extends SimpleNode {
  public AST_Declaration_Tuple_Named_Arg(int id) {
    super(id);
  }

  public AST_Declaration_Tuple_Named_Arg(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dfa5dae8f2f19ced4a28cc6cee0f9d68 (do not edit this line) */
