/* Generated By:JJTree: Do not edit this line. AST_Declaration_TypeList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_TypeList extends SimpleNode {
  public AST_Declaration_TypeList(int id) {
    super(id);
  }

  public AST_Declaration_TypeList(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7eb70b4f93e23b6e18cbbaa388c23ba (do not edit this line) */
