/* Generated By:JJTree: Do not edit this line. AST_Type_Primitive.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Type_Primitive extends SimpleNode {
  public AST_Type_Primitive(int id) {
    super(id);
  }

  public AST_Type_Primitive(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc9d139f5320786555d9b93e545790f1 (do not edit this line) */
