/* Generated By:JJTree: Do not edit this line. AST_Expression_Conditional_If_False.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Expression_Conditional_If_False extends SimpleNode {
  public AST_Expression_Conditional_If_False(int id) {
    super(id);
  }

  public AST_Expression_Conditional_If_False(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9adc5a88ad2c0eb5782ef9900574aee8 (do not edit this line) */
