/* Generated By:JJTree: Do not edit this line. AST_VariableDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_VariableDeclaration extends SimpleNode {
  public AST_VariableDeclaration(int id) {
    super(id);
  }

  public AST_VariableDeclaration(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=177986ee772cbed17ba2fa5fefd65411 (do not edit this line) */
