/* Generated By:JJTree: Do not edit this line. AST_Declaration_Function_Lambda_Nomod.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Function_Lambda_Nomod extends SimpleNode {
  public AST_Declaration_Function_Lambda_Nomod(int id) {
    super(id);
  }

  public AST_Declaration_Function_Lambda_Nomod(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16d48799aa4329f440d488fac9b0c715 (do not edit this line) */
