/* Generated By:JJTree: Do not edit this line. AST_Id.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Id extends SimpleNode {
  public AST_Id(int id) {
    super(id);
  }

  public AST_Id(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d5ead0cb2a9f8dab27aeae4bf7c06a70 (do not edit this line) */
