/* Generated By:JJTree: Do not edit this line. AST_Expression_Wrapped.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Expression_Wrapped extends SimpleNode {
  public AST_Expression_Wrapped(int id) {
    super(id);
  }

  public AST_Expression_Wrapped(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97255006047866aa369937271995be31 (do not edit this line) */
