/* Generated By:JJTree: Do not edit this line. AST_Statement_For_InitBranch.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_For_InitBranch extends SimpleNode {
  public AST_Statement_For_InitBranch(int id) {
    super(id);
  }

  public AST_Statement_For_InitBranch(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d5df16f9ea84e9630dd9be60995927c4 (do not edit this line) */
