/* Generated By:JJTree: Do not edit this line. AST_Declaration_EnumBody_Struct_Bodyless.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_EnumBody_Struct_Bodyless extends SimpleNode {
  public AST_Declaration_EnumBody_Struct_Bodyless(int id) {
    super(id);
  }

  public AST_Declaration_EnumBody_Struct_Bodyless(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1f82232b6612240bd0d5962b0b3f1b6 (do not edit this line) */
