/* Generated By:JJTree: Do not edit this line. AST_Statement_Labeled.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_Labeled extends SimpleNode {
  public AST_Statement_Labeled(int id) {
    super(id);
  }

  public AST_Statement_Labeled(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1fb225e721b962dc6d10de0228c53d6d (do not edit this line) */
