/* Generated By:JJTree: Do not edit this line. AST_Root.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Root extends SimpleNode {
  public AST_Root(int id) {
    super(id);
  }

  public AST_Root(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2bc677db2a1bfd952ebfa39ad89dbc6b (do not edit this line) */
