/* Generated By:JJTree: Do not edit this line. AST_Statement_If.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_If extends SimpleNode {
  public AST_Statement_If(int id) {
    super(id);
  }

  public AST_Statement_If(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e48a3e91369ca91880866ed58ae73e82 (do not edit this line) */
