/* Generated By:JJTree: Do not edit this line. AST_Declaration_Struct.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Struct extends SimpleNode {
  public AST_Declaration_Struct(int id) {
    super(id);
  }

  public AST_Declaration_Struct(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b59c2add4f7fe7308c2c9e4351cf3b65 (do not edit this line) */
