/* Generated By:JJTree: Do not edit this line. AST_Literal_Primitive_Suffix_Custom.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Literal_Primitive_Suffix_Custom extends SimpleNode {
  public AST_Literal_Primitive_Suffix_Custom(int id) {
    super(id);
  }

  public AST_Literal_Primitive_Suffix_Custom(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6563ef7bce6ee4aab73ab093413faa32 (do not edit this line) */
