/* Generated By:JJTree: Do not edit this line. AST_Type_Suffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Type_Suffix extends SimpleNode {
  public AST_Type_Suffix(int id) {
    super(id);
  }

  public AST_Type_Suffix(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05ffd9a59dba277109c87c07a958eea6 (do not edit this line) */
