/* Generated By:JJTree: Do not edit this line. AST_Statement_Switch_Line_Body_List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_Switch_Line_Body_List extends SimpleNode {
  public AST_Statement_Switch_Line_Body_List(int id) {
    super(id);
  }

  public AST_Statement_Switch_Line_Body_List(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2f106b98461bc7a4c0da2734f04051e6 (do not edit this line) */
