/* Generated By:JJTree: Do not edit this line. AST_Declaration_Function_Lambda_Enum.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Function_Lambda_Enum extends SimpleNode {
  public AST_Declaration_Function_Lambda_Enum(int id) {
    super(id);
  }

  public AST_Declaration_Function_Lambda_Enum(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9bf9e6bf72f9a5c7a6b96819c30e903f (do not edit this line) */
