/* Generated By:JJTree: Do not edit this line. AST_Declaration_VarObj_Single.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_VarObj_Single extends SimpleNode {
  public AST_Declaration_VarObj_Single(int id) {
    super(id);
  }

  public AST_Declaration_VarObj_Single(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=969de18228f6cb095c3282b5519c44c1 (do not edit this line) */
