/* Generated By:JJTree: Do not edit this line. AST_Statement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement extends SimpleNode {
  public AST_Statement(int id) {
    super(id);
  }

  public AST_Statement(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c01f4f819be69fc2a265fb7e21a919b3 (do not edit this line) */
