/* Generated By:JJTree: Do not edit this line. AST_Assignment.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Assignment extends SimpleNode {
  public AST_Assignment(int id) {
    super(id);
  }

  public AST_Assignment(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b8fdc1bce1a35556bf032f6c96dd1f6 (do not edit this line) */
