/* Generated By:JJTree: Do not edit this line. AST_Declaration_Variable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_Variable extends SimpleNode {
  public AST_Declaration_Variable(int id) {
    super(id);
  }

  public AST_Declaration_Variable(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf6d5a3346a286f2e9da50a2e5b60a30 (do not edit this line) */
