/* Generated By:JJTree: Do not edit this line. AST_AllConstructs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_AllConstructs extends SimpleNode {
  public AST_AllConstructs(int id) {
    super(id);
  }

  public AST_AllConstructs(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f271eb86f202fe524cfdea33fc128451 (do not edit this line) */
