/* Generated By:JJTree: Do not edit this line. AST_Type_Primitive_Tuple.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Type_Primitive_Tuple extends SimpleNode {
  public AST_Type_Primitive_Tuple(int id) {
    super(id);
  }

  public AST_Type_Primitive_Tuple(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a8a60f495f4e76690523b9e864162e1e (do not edit this line) */
