/* Generated By:JJTree: Do not edit this line. AST_Literal_Primitive_Suffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Literal_Primitive_Suffix extends SimpleNode {
  public AST_Literal_Primitive_Suffix(int id) {
    super(id);
  }

  public AST_Literal_Primitive_Suffix(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4416ffa745e66ec21dd1b7552003239 (do not edit this line) */
