/* Generated By:JJTree: Do not edit this line. AST_All.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_All extends SimpleNode {
  public AST_All(int id) {
    super(id);
  }

  public AST_All(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a14f5c0965740ad1a6240256d8021e7e (do not edit this line) */
