/* Generated By:JJTree: Do not edit this line. AST_Type_Primitive_Tuple_TypesOnly.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Type_Primitive_Tuple_TypesOnly extends SimpleNode {
  public AST_Type_Primitive_Tuple_TypesOnly(int id) {
    super(id);
  }

  public AST_Type_Primitive_Tuple_TypesOnly(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d53e3d4b11cfe0e2098b0a8a705ca638 (do not edit this line) */
