/* Generated By:JJTree: Do not edit this line. AST_Statement_Switch_Match_Single.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Statement_Switch_Match_Single extends SimpleNode {
  public AST_Statement_Switch_Match_Single(int id) {
    super(id);
  }

  public AST_Statement_Switch_Match_Single(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c1f25365c8f99813b06a13a616bc4ccb (do not edit this line) */
