/* Generated By:JJTree: Do not edit this line. AST_Declaration_VarObj_List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Declaration_VarObj_List extends SimpleNode {
  public AST_Declaration_VarObj_List(int id) {
    super(id);
  }

  public AST_Declaration_VarObj_List(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=333ff8dc2c60e350302f431f91a1e3b4 (do not edit this line) */
