/* Generated By:JJTree: Do not edit this line. AST_LabeledStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_LabeledStatement extends SimpleNode {
  public AST_LabeledStatement(int id) {
    super(id);
  }

  public AST_LabeledStatement(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e443a678b15ce8ad380a40eddc79099 (do not edit this line) */
