/* Generated By:JJTree: Do not edit this line. AST_Expression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_Expression extends SimpleNode {
  public AST_Expression(int id) {
    super(id);
  }

  public AST_Expression(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14f70f0c5c1a4f5451058b3e9bcec398 (do not edit this line) */
