/* Generated By:JJTree: Do not edit this line. AST_GlobalDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_GlobalDeclaration extends SimpleNode {
  public AST_GlobalDeclaration(int id) {
    super(id);
  }

  public AST_GlobalDeclaration(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8253b3514821f29472b4a0c14f68173b (do not edit this line) */
