/* Generated By:JJTree: Do not edit this line. AST_LocalDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_LocalDeclaration extends SimpleNode {
  public AST_LocalDeclaration(int id) {
    super(id);
  }

  public AST_LocalDeclaration(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fba47e17f7d334400895faaf8761b736 (do not edit this line) */
