/* Generated By:JJTree: Do not edit this line. AST_FunctionDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=CustomNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.parser;

public
class AST_FunctionDeclaration extends SimpleNode {
  public AST_FunctionDeclaration(int id) {
    super(id);
  }

  public AST_FunctionDeclaration(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f06fe1d7f851b6e2261c8c7c1834662e (do not edit this line) */
