/* Generated By:JavaCC: Do not edit this line. ScriptlangParserTreeConstants.java Version 6.0_1 */
package com.parser;

public interface ScriptlangParserTreeConstants
{
  public int JJT_ROOT = 0;
  public int JJTVOID = 1;
  public int JJT_EXPRESSION = 2;
  public int JJT_BLOCKUNIT = 3;
  public int JJT_DECLARATION_VARIABLE = 4;
  public int JJT_DECLARATION_FUNCTION = 5;
  public int JJT_DECLARATION_FUNCTION_LAMBDA = 6;
  public int JJT_DECLARATION_FUNCTION_LAMBDA_NOMOD = 7;
  public int JJT_DECLARATION_STRUCT = 8;
  public int JJT_DECLARATION_CLASS = 9;
  public int JJT_DECLARATION_CLASS_INHERITANCE = 10;
  public int JJT_DECLARATION_ENUM = 11;
  public int JJT_DECLARATION_ENUMBODY_CONST = 12;
  public int JJT_DECLARATION_ENUMBODY_STRUCT = 13;
  public int JJT_DECLARATION_ENUMBODY_STRUCT_BODYLESS = 14;
  public int JJT_DECLARATION_TUPLE = 15;
  public int JJT_DECLARATION_TYPELIST = 16;
  public int JJT_DECLARATION_PARAMETER_LIST = 17;
  public int JJT_DECLARATION_PARAMETER_SINGLE = 18;
  public int JJT_DECLARATION_PARAMETER_CALLER_LIST = 19;
  public int JJT_DECLARATION_PARAMETER_CALLER_SINGLE = 20;
  public int JJT_ASSIGNMENT = 21;
  public int JJT_IDENTIFIER = 22;
  public int JJT_LITERAL = 23;
  public int JJT_STATEMENT_LABELED = 24;
  public int JJT_STATEMENT_IF = 25;
  public int JJT_STATEMENT_IF_TRUE = 26;
  public int JJT_STATEMENT_IF_FALSE = 27;
  public int JJT_STATEMENT_SWITCH = 28;
  public int JJT_STATEMENT_FOR = 29;
  public int JJT_STATEMENT_WHILE = 30;
  public int JJT_TYPE_PRIMITIVE = 31;
  public int JJT_TYPE_MODIFIER = 32;


  public String[] jjtNodeName = {
    "_Root",
    "void",
    "_Expression",
    "_BlockUnit",
    "_Declaration_Variable",
    "_Declaration_Function",
    "_Declaration_Function_Lambda",
    "_Declaration_Function_Lambda_Nomod",
    "_Declaration_Struct",
    "_Declaration_Class",
    "_Declaration_Class_Inheritance",
    "_Declaration_Enum",
    "_Declaration_EnumBody_Const",
    "_Declaration_EnumBody_Struct",
    "_Declaration_EnumBody_Struct_Bodyless",
    "_Declaration_Tuple",
    "_Declaration_TypeList",
    "_Declaration_Parameter_List",
    "_Declaration_Parameter_Single",
    "_Declaration_Parameter_Caller_List",
    "_Declaration_Parameter_Caller_Single",
    "_Assignment",
    "_Identifier",
    "_Literal",
    "_Statement_Labeled",
    "_Statement_If",
    "_Statement_If_True",
    "_Statement_If_False",
    "_Statement_Switch",
    "_Statement_For",
    "_Statement_While",
    "_Type_Primitive",
    "_Type_Modifier",
  };
}
/* JavaCC - OriginalChecksum=f6e4b0621922f09ed625d415da495acc (do not edit this line) */
