/* Generated By:JJTree&JavaCC: Do not edit this line. ScriptlangParserConstants.java */
/** ScriptLangParser Class - BEGIN **/
package com.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScriptlangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int U8 = 7;
  /** RegularExpression Id. */
  int U16 = 8;
  /** RegularExpression Id. */
  int U32 = 9;
  /** RegularExpression Id. */
  int U64 = 10;
  /** RegularExpression Id. */
  int I8 = 11;
  /** RegularExpression Id. */
  int I16 = 12;
  /** RegularExpression Id. */
  int I32 = 13;
  /** RegularExpression Id. */
  int I64 = 14;
  /** RegularExpression Id. */
  int F32 = 15;
  /** RegularExpression Id. */
  int F64 = 16;
  /** RegularExpression Id. */
  int BOOL = 17;
  /** RegularExpression Id. */
  int CHAR = 18;
  /** RegularExpression Id. */
  int USIZE = 19;
  /** RegularExpression Id. */
  int ISIZE = 20;
  /** RegularExpression Id. */
  int AUTO = 21;
  /** RegularExpression Id. */
  int INT_LITERAL = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\"u8\"",
    "\"u16\"",
    "\"u32\"",
    "\"u64\"",
    "\"i8\"",
    "\"i16\"",
    "\"i32\"",
    "\"i64\"",
    "\"f32\"",
    "\"f64\"",
    "\"bool\"",
    "\"char\"",
    "\"usize\"",
    "\"isize\"",
    "\"auto\"",
    "<INT_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\",\"",
    "\":\"",
  };

}
