/* Generated By:JJTree&JavaCC: Do not edit this line. ScriptlangParserConstants.java */
/** ScriptLangParser Class - BEGIN **/
package com.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScriptlangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;
  /** RegularExpression Id. */
  int U8 = 14;
  /** RegularExpression Id. */
  int U16 = 15;
  /** RegularExpression Id. */
  int U32 = 16;
  /** RegularExpression Id. */
  int U64 = 17;
  /** RegularExpression Id. */
  int I8 = 18;
  /** RegularExpression Id. */
  int I16 = 19;
  /** RegularExpression Id. */
  int I32 = 20;
  /** RegularExpression Id. */
  int I64 = 21;
  /** RegularExpression Id. */
  int F32 = 22;
  /** RegularExpression Id. */
  int F64 = 23;
  /** RegularExpression Id. */
  int BOOL = 24;
  /** RegularExpression Id. */
  int CHAR = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int USIZE = 27;
  /** RegularExpression Id. */
  int ISIZE = 28;
  /** RegularExpression Id. */
  int AUTO = 29;
  /** RegularExpression Id. */
  int ARRAY = 30;
  /** RegularExpression Id. */
  int TYPE = 31;
  /** RegularExpression Id. */
  int LITERAL_SUFFIX = 32;
  /** RegularExpression Id. */
  int LITERAL_INT_BIN = 33;
  /** RegularExpression Id. */
  int LITERAL_INT_OCT = 34;
  /** RegularExpression Id. */
  int LITERAL_INT_DEC = 35;
  /** RegularExpression Id. */
  int LITERAL_INT_HEX = 36;
  /** RegularExpression Id. */
  int LITERAL_FLOAT32 = 37;
  /** RegularExpression Id. */
  int LITERAL_FLOAT64 = 38;
  /** RegularExpression Id. */
  int LITERAL_BOOL = 39;
  /** RegularExpression Id. */
  int FN = 40;
  /** RegularExpression Id. */
  int CLASS = 41;
  /** RegularExpression Id. */
  int STRUCT = 42;
  /** RegularExpression Id. */
  int ENUM = 43;
  /** RegularExpression Id. */
  int PUB = 44;
  /** RegularExpression Id. */
  int PRIV = 45;
  /** RegularExpression Id. */
  int IF = 46;
  /** RegularExpression Id. */
  int ELSE = 47;
  /** RegularExpression Id. */
  int SWITCH = 48;
  /** RegularExpression Id. */
  int FOR = 49;
  /** RegularExpression Id. */
  int WHILE = 50;
  /** RegularExpression Id. */
  int BREAK = 51;
  /** RegularExpression Id. */
  int CONTINUE = 52;
  /** RegularExpression Id. */
  int RETURN = 53;
  /** RegularExpression Id. */
  int BIND = 54;
  /** RegularExpression Id. */
  int IDENTIFIER = 55;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 56;
  /** RegularExpression Id. */
  int STRING_LITERAL = 57;
  /** RegularExpression Id. */
  int LETTER = 58;
  /** RegularExpression Id. */
  int DIGIT_BIN = 59;
  /** RegularExpression Id. */
  int DIGIT_OCT = 60;
  /** RegularExpression Id. */
  int DIGIT_DEC = 61;
  /** RegularExpression Id. */
  int DIGIT_HEX = 62;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"{\"",
    "\"}\"",
    "\"u8\"",
    "\"u16\"",
    "\"u32\"",
    "\"u64\"",
    "\"i8\"",
    "\"i16\"",
    "\"i32\"",
    "\"i64\"",
    "\"f32\"",
    "\"f64\"",
    "\"bool\"",
    "\"char\"",
    "\"string\"",
    "\"usize\"",
    "\"isize\"",
    "\"auto\"",
    "\"array\"",
    "\"type\"",
    "<LITERAL_SUFFIX>",
    "<LITERAL_INT_BIN>",
    "<LITERAL_INT_OCT>",
    "<LITERAL_INT_DEC>",
    "<LITERAL_INT_HEX>",
    "<LITERAL_FLOAT32>",
    "<LITERAL_FLOAT64>",
    "<LITERAL_BOOL>",
    "\"fn\"",
    "\"class\"",
    "\"struct\"",
    "\"enum\"",
    "\"pub\"",
    "\"priv\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"for\"",
    "\"while\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"@\"",
    "<IDENTIFIER>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<DIGIT_BIN>",
    "<DIGIT_OCT>",
    "<DIGIT_DEC>",
    "<DIGIT_HEX>",
    "\":\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"+=\"",
    "\"-=\"",
    "\">>=\"",
    "\"<<=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
  };

}
