/* Generated By:JJTree: Do not edit this line. AST_Declaration_Array_Slice_End.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Array_Slice_End extends SimpleNode {
  public AST_Declaration_Array_Slice_End(int id) {
    super(id);
  }

  public AST_Declaration_Array_Slice_End(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d51405c2a901c2d6b3bfa9aa99d28ad9 (do not edit this line) */
