/* Generated By:JJTree: Do not edit this line. AST_BlockUnit_Thread.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_BlockUnit_Thread extends SimpleNode {
  public AST_BlockUnit_Thread(int id) {
    super(id);
  }

  public AST_BlockUnit_Thread(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ccc5609cf78cfce88e0c24d9dbbb40d0 (do not edit this line) */
