/* Generated By:JJTree: Do not edit this line. AST_Statement_Switch_Line_List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Switch_Line_List extends SimpleNode {
  public AST_Statement_Switch_Line_List(int id) {
    super(id);
  }

  public AST_Statement_Switch_Line_List(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=16c42849583cf926f163b50f13dd01a1 (do not edit this line) */
