/* Generated By:JJTree: Do not edit this line. AST_Statement_For_BodyBranch.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_For_BodyBranch extends SimpleNode {
  public AST_Statement_For_BodyBranch(int id) {
    super(id);
  }

  public AST_Statement_For_BodyBranch(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=4f0a30b38de131fa951fadc93e48476b (do not edit this line) */
