/* Generated By:JJTree: Do not edit this line. AST_Statement_While_BodyBranch.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_While_BodyBranch extends SimpleNode {
  public AST_Statement_While_BodyBranch(int id) {
    super(id);
  }

  public AST_Statement_While_BodyBranch(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6d5dfd5c96656ac23d87d37402520fa (do not edit this line) */
