/* Generated By:JJTree: Do not edit this line. AST_Assignment.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Assignment extends SimpleNode {
  public AST_Assignment(int id) {
    super(id);
  }

  public AST_Assignment(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=48549ca71fd23e756dec474a06bfdfc0 (do not edit this line) */
