/* Generated By:JJTree: Do not edit this line. AST_Statement_Switch_Line.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Switch_Line extends SimpleNode {
  public AST_Statement_Switch_Line(int id) {
    super(id);
  }

  public AST_Statement_Switch_Line(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ad8e6f68c776dd219b3e8d58e3409da (do not edit this line) */
