/* Generated By:JJTree: Do not edit this line. AST_Assignment_Operation.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Assignment_Operation extends SimpleNode {
  public AST_Assignment_Operation(int id) {
    super(id);
  }

  public AST_Assignment_Operation(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=e80beba7e2b42cb3fc4a0aed37ce1cab (do not edit this line) */
