/* Generated By:JJTree: Do not edit this line. AST_Declaration_Array_Slice_Skip.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Array_Slice_Skip extends SimpleNode {
  public AST_Declaration_Array_Slice_Skip(int id) {
    super(id);
  }

  public AST_Declaration_Array_Slice_Skip(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6c53314df87c3ccd3a793bfe1fc9db7 (do not edit this line) */
