/* Generated By:JJTree: Do not edit this line. AST_Declaration_Array_Slice_Start.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Array_Slice_Start extends SimpleNode {
  public AST_Declaration_Array_Slice_Start(int id) {
    super(id);
  }

  public AST_Declaration_Array_Slice_Start(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=f3be9b766b49ad2bab5e112ed1ed6eda (do not edit this line) */
