/* Generated By:JJTree: Do not edit this line. AST_Declaration_Class.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Class extends SimpleNode {
  public AST_Declaration_Class(int id) {
    super(id);
  }

  public AST_Declaration_Class(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73cf0ae1e26c2a35961d19b85a8505ed (do not edit this line) */
