/* Generated By:JJTree: Do not edit this line. AST_Declaration_Enum.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Enum extends SimpleNode {
  public AST_Declaration_Enum(int id) {
    super(id);
  }

  public AST_Declaration_Enum(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=515c858d52fcba87c47d3a34afa69209 (do not edit this line) */
