/* Generated By:JJTree: Do not edit this line. AST_Declaration_Parameter_List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Parameter_List extends SimpleNode {
  public AST_Declaration_Parameter_List(int id) {
    super(id);
  }

  public AST_Declaration_Parameter_List(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef70514a87d35510b8ffdce3e2ff4746 (do not edit this line) */
