/* Generated By:JJTree: Do not edit this line. AST_Declaration_Object.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Object extends SimpleNode {
  public AST_Declaration_Object(int id) {
    super(id);
  }

  public AST_Declaration_Object(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=422fd8372d8032e8f3865456f627a635 (do not edit this line) */
