/* Generated By:JJTree: Do not edit this line. AST_Declaration_Parameter_Single.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Parameter_Single extends SimpleNode {
  public AST_Declaration_Parameter_Single(int id) {
    super(id);
  }

  public AST_Declaration_Parameter_Single(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=3aa979caa7e9d59cce3ed954108a81e5 (do not edit this line) */
