/* Generated By:JJTree: Do not edit this line. AST_Statement_While.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_While extends SimpleNode {
  public AST_Statement_While(int id) {
    super(id);
  }

  public AST_Statement_While(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=8c4668f45ba15ad302a023795dbba8ea (do not edit this line) */
