/* Generated By:JJTree: Do not edit this line. AST_BlockUnit.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_BlockUnit extends SimpleNode {
  public AST_BlockUnit(int id) {
    super(id);
  }

  public AST_BlockUnit(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=bbd7c0acaa14def461ed4aa82631f811 (do not edit this line) */
