/* Generated By:JJTree: Do not edit this line. AST_Statement_Switch_Match_List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Switch_Match_List extends SimpleNode {
  public AST_Statement_Switch_Match_List(int id) {
    super(id);
  }

  public AST_Statement_Switch_Match_List(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c83ae39f6d34933972f7369d672a6e64 (do not edit this line) */
