/* Generated By:JJTree: Do not edit this line. AST_Declaration_Class_Inheritance.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Class_Inheritance extends SimpleNode {
  public AST_Declaration_Class_Inheritance(int id) {
    super(id);
  }

  public AST_Declaration_Class_Inheritance(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48fc5572e2d8bfca7d38a8a2b49346f1 (do not edit this line) */
