/* Generated By:JJTree: Do not edit this line. AST_Literal.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Literal extends SimpleNode {
  public AST_Literal(int id) {
    super(id);
  }

  public AST_Literal(ScriptlangParser p, int id) {
    super(p, id);
  }

  public Node legalize(Node parent, int astDepth) {
	  return null;
  }
  
}
/* JavaCC - OriginalChecksum=73a9b563193c8d49db0e1a830c14890d (do not edit this line) */
