/* Generated By:JJTree: Do not edit this line. AST_Declaration_Function_Lambda.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Function_Lambda extends SimpleNode {
  public AST_Declaration_Function_Lambda(int id) {
    super(id);
  }

  public AST_Declaration_Function_Lambda(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=a3f295346fe17be8c657296abc41a9b8 (do not edit this line) */
