/* Generated By:JJTree: Do not edit this line. AST_Statement_If_True.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_If_True extends SimpleNode {
  public AST_Statement_If_True(int id) {
    super(id);
  }

  public AST_Statement_If_True(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de377c8b73740a3b12c7d21dd69c780b (do not edit this line) */
