/* Generated By:JJTree: Do not edit this line. AST_Declaration_Array_Slice.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Array_Slice extends SimpleNode {
  public AST_Declaration_Array_Slice(int id) {
    super(id);
  }

  public AST_Declaration_Array_Slice(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0fd1fdc1c6b15206f3a173992e6c1e10 (do not edit this line) */
