/* Generated By:JJTree: Do not edit this line. AST_Statement_For.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_For extends SimpleNode {
  public AST_Statement_For(int id) {
    super(id);
  }

  public AST_Statement_For(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6a9f90bd47213bc61c0b83321f729e2 (do not edit this line) */
