/* Generated By:JJTree: Do not edit this line. AST_Declaration_Tuple_Arg.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Tuple_Arg extends SimpleNode {
  public AST_Declaration_Tuple_Arg(int id) {
    super(id);
  }

  public AST_Declaration_Tuple_Arg(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed96c5e0ea1287fbd0c33cd3514eaf36 (do not edit this line) */
