/* Generated By:JJTree: Do not edit this line. AST_BlockUnit_Unsafe.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_BlockUnit_Unsafe extends SimpleNode {
  public AST_BlockUnit_Unsafe(int id) {
    super(id);
  }

  public AST_BlockUnit_Unsafe(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=655da9cebb56eec813917dd42ba38c45 (do not edit this line) */
