/* Generated By:JJTree: Do not edit this line. AST_Statement_Empty.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Empty extends SimpleNode {
  public AST_Statement_Empty(int id) {
    super(id);
  }

  public AST_Statement_Empty(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=b9e2ec54098a6257006dba229a135074 (do not edit this line) */
