/* Generated By:JJTree: Do not edit this line. AST_Declaration_Array.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Array extends SimpleNode {
  public AST_Declaration_Array(int id) {
    super(id);
  }

  public AST_Declaration_Array(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1a3ebdec5a592ee80e77c5ab56a11fc (do not edit this line) */
