/* Generated By:JJTree: Do not edit this line. AST_Expression_Conditional_If_True.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Expression_Conditional_If_True extends SimpleNode {
  public AST_Expression_Conditional_If_True(int id) {
    super(id);
  }

  public AST_Expression_Conditional_If_True(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=bab391e10f5d1c284a5488c1048f941a (do not edit this line) */
