/* Generated By:JJTree: Do not edit this line. AST_Identifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Identifier extends SimpleNode {
  public AST_Identifier(int id) {
    super(id);
  }

  public AST_Identifier(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50901840243876635ae46248bfb23d39 (do not edit this line) */
