/* Generated By:JJTree: Do not edit this line. AST_Statement_Flow.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Flow extends SimpleNode {
  public AST_Statement_Flow(int id) {
    super(id);
  }

  public AST_Statement_Flow(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ca79f083a19db6ad334507270c60fbd1 (do not edit this line) */
