/* Generated By:JJTree: Do not edit this line. AST_Statement_Expression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Expression extends SimpleNode {
  public AST_Statement_Expression(int id) {
    super(id);
  }

  public AST_Statement_Expression(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=59b44e7e9c629a11b6ce5bbb96b71e65 (do not edit this line) */
