/* Generated By:JJTree: Do not edit this line. AST_Type.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Type extends SimpleNode {
  public AST_Type(int id) {
    super(id);
  }

  public AST_Type(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30eb1c2b745e28764dc1d8a374e7df82 (do not edit this line) */
