/* Generated By:JJTree: Do not edit this line. AST_Declaration_EnumBody_Tuple.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_EnumBody_Tuple extends SimpleNode {
  public AST_Declaration_EnumBody_Tuple(int id) {
    super(id);
  }

  public AST_Declaration_EnumBody_Tuple(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=416aee5a90755c05925f110765dd244e (do not edit this line) */
