/* Generated By:JJTree: Do not edit this line. AST_Statement_Switch.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Switch extends SimpleNode {
  public AST_Statement_Switch(int id) {
    super(id);
  }

  public AST_Statement_Switch(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4bdc4fe77681755b0509976c6288dd98 (do not edit this line) */
