/* Generated By:JJTree: Do not edit this line. AST_Statement_Foreach_InitBranch.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Statement_Foreach_InitBranch extends SimpleNode {
  public AST_Statement_Foreach_InitBranch(int id) {
    super(id);
  }

  public AST_Statement_Foreach_InitBranch(ScriptlangParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2797d6268c08972c69a491b40b67b32b (do not edit this line) */
