/* Generated By:JJTree: Do not edit this line. AST_Declaration_Object_List.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=NodeSetter,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.slang.frontend.parser;

public
class AST_Declaration_Object_List extends SimpleNode {
  public AST_Declaration_Object_List(int id) {
    super(id);
  }

  public AST_Declaration_Object_List(ScriptlangParser p, int id) {
    super(p, id);
  }
  
  public Node legalize(Node parent, int astDepth) {
	  return null;
  }

}
/* JavaCC - OriginalChecksum=c7d2486f9ee1ae9ff0c870163d117ca7 (do not edit this line) */
