/* Generated By:JavaCC: Do not edit this line. ScriptlangParserTreeConstants.java Version 6.0_1 */
package com.slang.frontend.parser;

public interface ScriptlangParserTreeConstants
{
  public int JJT_ROOT = 0;
  public int JJTVOID = 1;
  public int JJT_LABEL = 2;
  public int JJT_TYPE = 3;
  public int JJT_BLOCKUNIT_THREAD = 4;
  public int JJT_BLOCKUNIT_THREAD_UNSAFE = 5;
  public int JJT_BLOCKUNIT = 6;
  public int JJT_BLOCKUNIT_UNSAFE = 7;
  public int JJT_STATEMENT_EMPTY = 8;
  public int JJT_TERMINATOR = 9;
  public int JJT_DECLARATION_OBJECT = 10;
  public int JJT_DECLARATION_OBJECT_LIST = 11;
  public int JJT_DECLARATION_FUNCTION_LAMBDA = 12;
  public int JJT_DECLARATION_OBJECT_SINGLE = 13;
  public int JJT_DECLARATION_FUNCTION = 14;
  public int JJT_DECLARATION_STRUCT = 15;
  public int JJT_DECLARATION_CLASS = 16;
  public int JJT_DECLARATION_CLASS_INHERITANCE = 17;
  public int JJT_DECLARATION_ENUM = 18;
  public int JJT_DECLARATION_ENUMBODY_CONST = 19;
  public int JJT_DECLARATION_ENUMBODY_STRUCT = 20;
  public int JJT_DECLARATION_ENUMBODY_TUPLE = 21;
  public int JJT_DECLARATION_ENUMBODY_TUPLE_ARG = 22;
  public int JJT_DECLARATION_BIND = 23;
  public int JJT_DECLARATION_PARAMETER_LIST = 24;
  public int JJT_DECLARATION_PARAMETER_SINGLE = 25;
  public int JJT_DECLARATION_PARAMETER_CALLER_LIST = 26;
  public int JJT_DECLARATION_PARAMETER_CALLER_SINGLE = 27;
  public int JJT_EXPRESSION = 28;
  public int JJT_DECLARATION_ARRAY_ARG = 29;
  public int JJT_DECLARATION_ARRAY = 30;
  public int JJT_DECLARATION_ARRAY_SLICE = 31;
  public int JJT_DECLARATION_ARRAY_SLICE_START = 32;
  public int JJT_DECLARATION_ARRAY_SLICE_END = 33;
  public int JJT_DECLARATION_ARRAY_SLICE_SKIP = 34;
  public int JJT_DECLARATION_TUPLE = 35;
  public int JJT_DECLARATION_TUPLE_ARG = 36;
  public int JJT_ASSIGNMENT = 37;
  public int JJT_ASSIGNMENT_OPERATION = 38;
  public int JJT_IDENTIFIER = 39;
  public int JJT_LITERAL = 40;
  public int JJT_LITERAL_PRIMITIVE_SUFFIX_CUSTOM = 41;
  public int JJT_EXPRESSION_CONDITIONAL_IF_TRUE = 42;
  public int JJT_EXPRESSION_CONDITIONAL_IF_FALSE = 43;
  public int JJT_STATEMENT_EXPRESSION = 44;
  public int JJT_STATEMENT_IF = 45;
  public int JJT_STATEMENT_IF_TRUE = 46;
  public int JJT_STATEMENT_IF_FALSE = 47;
  public int JJT_STATEMENT_SWITCH = 48;
  public int JJT_STATEMENT_SWITCH_MATCH_LIST = 49;
  public int JJT_STATEMENT_SWITCH_LINE_LIST = 50;
  public int JJT_STATEMENT_SWITCH_LINE = 51;
  public int JJT_STATEMENT_SWITCH_LINE_BODY_LIST = 52;
  public int JJT_STATEMENT_FOR = 53;
  public int JJT_STATEMENT_FOREACH_INITBRANCH = 54;
  public int JJT_STATEMENT_FOR_INITBRANCH = 55;
  public int JJT_STATEMENT_FOR_ITERATEBRANCH = 56;
  public int JJT_STATEMENT_FOR_BODYBRANCH = 57;
  public int JJT_STATEMENT_WHILE = 58;
  public int JJT_STATEMENT_WHILE_BODYBRANCH = 59;
  public int JJT_STATEMENT_FLOW = 60;


  public String[] jjtNodeName = {
    "_Root",
    "void",
    "_Label",
    "_Type",
    "_BlockUnit_Thread",
    "_BlockUnit_Thread_Unsafe",
    "_BlockUnit",
    "_BlockUnit_Unsafe",
    "_Statement_Empty",
    "_Terminator",
    "_Declaration_Object",
    "_Declaration_Object_List",
    "_Declaration_Function_Lambda",
    "_Declaration_Object_Single",
    "_Declaration_Function",
    "_Declaration_Struct",
    "_Declaration_Class",
    "_Declaration_Class_Inheritance",
    "_Declaration_Enum",
    "_Declaration_EnumBody_Const",
    "_Declaration_EnumBody_Struct",
    "_Declaration_EnumBody_Tuple",
    "_Declaration_EnumBody_Tuple_Arg",
    "_Declaration_Bind",
    "_Declaration_Parameter_List",
    "_Declaration_Parameter_Single",
    "_Declaration_Parameter_Caller_List",
    "_Declaration_Parameter_Caller_Single",
    "_Expression",
    "_Declaration_Array_Arg",
    "_Declaration_Array",
    "_Declaration_Array_Slice",
    "_Declaration_Array_Slice_Start",
    "_Declaration_Array_Slice_End",
    "_Declaration_Array_Slice_Skip",
    "_Declaration_Tuple",
    "_Declaration_Tuple_Arg",
    "_Assignment",
    "_Assignment_Operation",
    "_Identifier",
    "_Literal",
    "_Literal_Primitive_Suffix_Custom",
    "_Expression_Conditional_If_True",
    "_Expression_Conditional_If_False",
    "_Statement_Expression",
    "_Statement_If",
    "_Statement_If_True",
    "_Statement_If_False",
    "_Statement_Switch",
    "_Statement_Switch_Match_List",
    "_Statement_Switch_Line_List",
    "_Statement_Switch_Line",
    "_Statement_Switch_Line_Body_List",
    "_Statement_For",
    "_Statement_Foreach_InitBranch",
    "_Statement_For_InitBranch",
    "_Statement_For_IterateBranch",
    "_Statement_For_BodyBranch",
    "_Statement_While",
    "_Statement_While_BodyBranch",
    "_Statement_Flow",
  };
}
/* JavaCC - OriginalChecksum=0fee6807b33e1b8a1974af164177fd03 (do not edit this line) */
